# Generated by Django 2.2.13 on 2020-09-06 11:50

from django.db import migrations, models
import djongo.models.fields
import submission.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Offered Price')),
                ('creator', models.CharField(max_length=200)),
                ('submissions', djongo.models.fields.ArrayField(default=[], model_container=submission.models.Submission)),
                ('deadline', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('ranked', models.BooleanField()),
                ('date_posted', models.DateField()),
                ('level', models.IntegerField(default=1)),
            ],
        ),
    ]
